bug_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('bug_tracker_app.urls'))
]

bug_tracker_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index),
    path('login', views.login),
    path('register', views.register),
    path('login/success', views.user_login),
    path('login/register', views.user_registration),
    path('projects', views.projects),
    path('tickets', views.tickets),
    path('projects/add', views.add_project),
    path('projects/<int:projectid>', views.view_project),
    path('projects/<int:projectid>/add_user', views.add_project_user),
    path('tickets/add', views.add_ticket),
    path('comments/add', views.comment),
    path('comments/<int:commentid>/delete', views.delete_comment),
    path('tickets/<int:ticketid>', views.ticket_view),
    path('tickets/comments/add', views.add_ticket_comment),
    path('tickets/comments/<int:commentid>/delete', views.delete_ticket_comment),
    path('tickets/<int:ticketid>/delete', views.delete_ticket),
    path('tickets/<int:ticketid>/submit', views.submit_ticket),
    path('tickets/<int:ticketid>/resolve', views.resolve_ticket),
    path('tickets/<int:ticketid>/edit', views.edit_ticket),
    path('tickets/<int:ticketid>/edit/success', views.edit_ticket_submit),
    path('user/<int:userid>', views.user),
    path('user/<int:userid>/edit', views.edit_user),
    path('admin', views.admin),
    path('admin/<int:userid>/edit', views.admin_edit_user),
    path('admin/users/<int:userid>/delete', views.admin_delete_user),
    path('logout', views.logout),
    path('about', views.about)
]

bug_tracker_app/models.py
from django.db import models
import re
import bcrypt

# Create your models here.
class UserManager(models.Manager):
    def register_validator(self, postData):
        errors = {}
        EMAIL_REGEX = re.compile(r"^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$")
        # PASSWORD_REGEX = re.compile(r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$")
        if len(postData['first_name']) < 2 or len(postData['last_name']) < 2:
            errors["name"] = "First and Last name should contain at least 2 characters"
        if len(User.objects.filter(email=postData['email'])) > 0:
            errors["emailAlreadyExists"] = "A user with this email already exists"
        if not EMAIL_REGEX.match(postData['email']):
            errors["emailValid"] = "Please enter a valid email"
        if len(postData['password'])<8:
            errors["passwordValid"] = "Passwords must be at least 8 characters long"
        if postData['password'] != postData['password_confirm']:
            errors["passwordMatch"] = "Password and Confirm password must match"
        return errors
    
    def login_validator(self, postData):
        try:
            user = User.objects.filter(email = postData['email'])
            errors = {}
            if user:
                logged_user = user[0]
                if bcrypt.checkpw(postData['password'].encode(), logged_user.password.encode()):
                    return errors
                else:
                    errors['passwordUserMatch'] = "Incorrect email and password combination"
                return errors
            else:
                errors['userNotFound'] = "No user associated with this email address"    
            return errors
        except:
            errors['nouser'] = "no user"
            return errors

class CompanyManager(models.Manager):
    def company_validator(self, postData):
        errors = {}
        if postData['company_code'] != "":
            try:
                company_code = postData["company_code"]
                company_code_hash = bcrypt.hashpw(company_code.encode(), bcrypt.gensalt()).decode()
                company_name = postData["old_company_name"]
                company = Company.objects.filter(company_name = company_name)
                if company:
                    this_company = company[0]
                    print('hello')
                    if bcrypt.checkpw(postData['company_code'].encode(), this_company.company_code.encode()):
                        print('hello world')
                        return errors
                    else:
                        errors['CodeNotFound'] = "Company code not found2"
                else:
                    errors['companyNotFound'] = "Company code not found3"
                return errors
            except:
                error['companyNotFound'] = "Company code not found 1"
        elif postData['company_name'] != "" and postData['new_company_code'] != "":
            if len(Company.objects.filter(company_name=postData['company_name'])) > 0:
                errors['companyAlreadyExists'] = "A company with this name already exists"
            if len(postData['new_company_code']) < 6:
                errros['companyCodeLength'] = 'Company code must be at least 6 characters'
            return errors

class Company(models.Model):
    company_name = models.CharField(max_length=255)
    company_code = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = CompanyManager()

class User(models.Model):
    USER_ROLE_CHOICES = (
        (1, 'developer'),
        (2, 'project_manager'),
        (3, 'admin'),
    )   

    user_role = models.PositiveSmallIntegerField(choices=USER_ROLE_CHOICES, default=1)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    company = models.ForeignKey(Company, related_name="users", on_delete=models.CASCADE)
    objects = UserManager()

class Project(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    project_manager = models.ForeignKey(User, related_name="projects_managed", on_delete=models.CASCADE, null=True)
    created_by = models.ForeignKey(User, related_name="created_projects", on_delete=models.CASCADE)
    users = models.ManyToManyField(User, related_name="current_projects", null=True)
    company = models.ForeignKey(Company, related_name="projects", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Ticket(models.Model):
    PRIORITY_CHOICES = (
        (1, 'low'),
        (2, 'medium'),
        (3, 'high'),
    )

    STATUS_CHOICES = (
        (1, 'unassigned'),
        (2, 'active'),
        (3, 'review'),
        (4, 'resolved'),
    ) 

    title = models.CharField(max_length=255)
    description = models.TextField()
    priority = models.PositiveSmallIntegerField(choices=PRIORITY_CHOICES)
    status = models.PositiveSmallIntegerField(choices=STATUS_CHOICES)
    project = models.ForeignKey(Project, related_name="tickets", on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name="current_tickets", on_delete=models.SET_NULL, null=True)
    company = models.ForeignKey(Company, related_name="tickets", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Report(models.Model):
    ticket = models.ForeignKey(Ticket, related_name="reports", on_delete=models.CASCADE)
    description = models.TextField()
    user = models.ForeignKey(User, related_name="reports", on_delete=models.CASCADE)
    assigned_by = models.ForeignKey(User, related_name="assigned_reports", on_delete=models.CASCADE)
    due_date = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    comment = models.TextField()
    user = models.ForeignKey(User, related_name="comments", on_delete=models.CASCADE)
    project = models.ForeignKey(Project, related_name="comments", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class TicketComment(models.Model):
    comment = models.TextField()
    user = models.ForeignKey(User, related_name="ticket_comments", on_delete=models.CASCADE)
    ticket = models.ForeignKey(Ticket, related_name="comments", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

bug_tracker_app/templates/admin.html
{% extends "base_layout.html" %}
{% block content %}
    <script>
        $(document).ready(function(){
            $(".edit-user").click(function() {
                var userForm = "." + this.id
                $(userForm).stop().toggle('slow');
            });
            $("#mobile-nav-btn").click(function() {
                $("#mobile-nav").toggle();
            });
            $("#show-users").click(function() {
                $(".project-users").toggle();
            }); 
            $(".delete-user").click(function() {
                var deleteUserForm = "." + this.id
                $(deleteUserForm).stop().toggle('slow')
            })
        })
    </script>
    <div id="cover"></div>
    <div class="container">

        {% include "header.html" %}

        <div class="sub-header box-shadow">
            <h2>Admin</h2>
        </div>
        <div>
            <div class="project-users box-shadow" id="admin-project-users">
                <h2>Users</h2>
                <ul>
                    {% for user in users %}
                    <li>{{ user.first_name }} {{ user.last_name }}
                        <button id="editUser{{ user.id }}" class="edit-user"><i class="far fa-edit"></i></button>
                        <button id="deleteUser{{ user.id }}"class="delete-user"><i class="fas fa-times"></i></button>
                        <div class="deleteUsers deleteUser{{ user.id }}">
                            <form action="/admin/users/{{ user.id }}/delete" method="post">
                                {% csrf_token %}
                                <p id="delete-warning">*** WARNING ***</p>
                                <p>This will permanently delete this user. Continue?</p>
                                <button id="delete-user-btn" type="submit">DELETE</button>
                            </form>
                        </div>
                        <div id="user{{ user.id }}" class="editUsers editUser{{ user.id }}">
                            <form action="/admin/{{ user.id }}/edit" method="post">
                                {% csrf_token %}
           
                                <label for="first_name">First Name</label>
                                <input type="text" name="first_name" value="{{ user.first_name }}">
                                <label for="last_name">Last Name</label>
                                <input type="text" name="last_name" value="{{ user.last_name }}">
                                <label for="email">Email</label>
                                <input type="email" name="email" value="{{ user.email }}">
                                <label for="role">User Role</label>
                                <select name="role" id="">
                                    <option value="{{ user.role }}">{{ user.get_role_display }}</option>
                                    <option value="1">Developer</option>
                                    <option value="2">Project Manager</option>
                                    <option value="3">Admin</option>
                                </select>
                                <button type="submit">Update</button>
                            </form>
                        </div>
                    </li>
                    {% endfor %}
                </ul>                
            </div>
            <button id="show-users">
                <i class="fas fa-angle-double-down fa-2x"></i>
            </button>  
            <div class="table-scroll" id="admin-table">
                <h2 id="admin-tickets">Tickets Pending Review</h2>
                <table class="project-tickets-table" id="project-active-tickets">
                    <tr>
                        <th class="mobile-table">Title</th>
                        <th class="desktop-table">Ticket ID</th>
                        <th class="desktop-table">Priority</th>
                        <th class="mobile-table">Project</th>
                        <th class="mobile-table">Assigned To</th>
                        <th class="desktop-table">Created On</th>
                        <th class="desktop-table">Updated On</th>
                        <th class="mobile-table">Action</th>
                    </tr>
                    {% for ticket in tickets %}
                    {% if ticket.project.project_manager.id == request.session.user_id and ticket.status == 3 %}
                    <tr id="ticketID{{ ticket.id }}">
                        <td class="mobile-table">{{ ticket.title }}</td>
                        <td class="desktop-table">{{ ticket.id }}</td>
                        <td class="desktop-table"><span class="dot" id="{{ ticket.get_priority_display }}"></span>{{ ticket.get_priority_display }}</td>
                        <td class="mobile-table">{{ ticket.project.title }}</td>
                        {% if ticket.status == 1 %}
                        <td class="mobile-table">Unassigned</td>
                        {% else %}
                        <td class="mobile-table">{{ ticket.user.first_name }} {{ ticket.user.last_name }}</td>
                        {% endif %}
                        <td class="desktop-table">{{ ticket.created_at }}</td>
                        <td class="desktop-table">{{ ticket.updated_at }}</td>
                        <td class="mobile-table"><button class="ticket-view" id="view-ticket"><a href="/tickets/{{ ticket.id }}">View</a></button> <button class="ticket-view" id="edit-ticket"><a href="/tickets/{{ ticket.id }}/edit">Edit</a></button></td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

bug_tracker_app/templates/base_layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@500;900&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Quicksand:wght@300&family=Roboto:wght@300&display=swap');
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://kit.fontawesome.com/f6fbc72d0a.js" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>

bug_tracker_app/templates/project_view.html
{% extends "base_layout.html" %}
{% block content %}
    <script>
        $(document).ready(function(){
            $("#openTicket").stop().click(function(){
                $("#addTicket").fadeIn("slow");
                $("#cover").fadeIn("fast");
            });
            
            $("#closeTicket").click(function() {
                $("#addTicket").hide();
                $("#cover").hide();
            })

            $("#view-resolved-btn").stop().click(function() {
                $("#active-table").stop().hide();
                $("#resolved-table").stop().fadeIn("slow").delay(1000);
                $("#view-resolved-btn").stop().hide();
                $("#view-active-btn").stop().show();
            })

            $("#view-active-btn").stop().click(function() {
                $("#active-table").stop().fadeIn("slow").delay(1000);
                $("#resolved-table").stop().hide();
                $("#view-resolved-btn").stop().show();
                $("#view-active-btn").stop().hide();
            })

            $("#mobile-nav-btn").click(function() {
                $("#mobile-nav").toggle();
            })

            $("#show-users").click(function() {
                $(".project-users").toggle();
            })
        })
    </script>
    <div class="container">
        <div id="cover"></div>

        {% include "header.html" %}

        <div class="sub-header box-shadow">
            <h2>{{ project.title }}</h2>
            <a href="/projects">Back to Projects</a>
        </div>
        <div class="project-view">
            <button id="show-users">
                <i class="fas fa-angle-double-down fa-2x"></i>
            </button>
            <div class="project-users box-shadow">
                <h2>Users</h2>
                <ul>
                    {% for user in users %}
                    <li>{{ user.first_name }} {{ user.last_name }}
                        {% if request.session.role in admin %}
                        <a href=""><i class="fas fa-times"></i></a>
                        {% endif %}
                    </li>
                    {% endfor %}
                </ul>
                {% if request.session.role == 2 or request.session.role == 3%}
                <form action="/projects/{{ project.id }}/add_user" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="project" value="{{ project.id }}">
                    <label for="add-project-user">Add a User</label>
                    <select name="add-project-user" id="add-project-user" required>
                        <option value=""></option>
                        {% for user in all_users %}
                        {% if user not in users %}
                        <option value="{{ user.id }}">{{ user.first_name }} {{ user.last_name }}</option>
                        {% endif %}
                        {% endfor %}
                    </select>
                    <button id="add-user" type="submit">Add User</button>
                </form>
                {% endif %}                    
            </div>
            <div class="project-tickets">
                <button id="view-resolved-btn">View Resolved Tickets</button>
                <button id="view-active-btn">View Active Tickets</button>
                <div id="active-table" class="table-scroll">
                    <h2>Active Tickets</h2>
                    <table class="project-tickets-table">
                        <tr>
                            <th>Title</th>
                            <th class="desktop-table">Ticket ID</th>
                            <th class="desktop-table">Priority</th>
                            <th>Project</th>
                            <th>Assigned To</th>
                            <th class="desktop-table">Created On</th>
                            <th class="desktop-table">Updated On</th>
                            <th>Action</th>
                        </tr>
                        {% for ticket in tickets %}
                        {% if ticket.status != 4 %}
                        <tr id="ticketID{{ ticket.id }}">
                            <td>{{ ticket.title }}</td>
                            <td class="desktop-table">{{ ticket.id }}</td>
                            <td class="desktop-table"><span class="dot" id="{{ ticket.get_priority_display }}"></span>{{ ticket.get_priority_display }}</td>
                            <td>{{ ticket.project.title }}</td>
                            {% if ticket.status == 1 %}
                            <td>Unassigned</td>
                            {% else %}
                            <td>{{ ticket.user.first_name }} {{ ticket.user.last_name }}</td>
                            {% endif %}
                            <td class="desktop-table">{{ ticket.created_at }}</td>
                            <td class="desktop-table">{{ ticket.updated_at }}</td>
                            <td>
                                <form action="/tickets/{{ ticket.id }}">
                                    <button class="ticket-view" id="view-ticket" type="submit">View</button>
                                </form>
                                <form action="/tickets/{{ ticket.id }}/edit">
                                    <button class="ticket-view" id="edit-ticket" type="submit">Edit</button></td>
                                </form>
                        </tr>
                        {% endif %}
                        {% endfor %}
                    </table>
                </div>
                <div id="resolved-table" class="table-scroll">
                    <h2>Resolved Tickets</h2>
                    <table class="project-tickets-table">
                        <tr>
                            <th class="mobile-table">Title</th>
                            <th class="desktop-table">Ticket ID</th>
                            <th class="desktop-table">Priority</th>
                            <th class="mobile-table">Project</th>
                            <th class="mobile-table">Assigned To</th>
                            <th class="desktop-table">Created On</th>
                            <th class="desktop-table">Updated On</th>
                            <th class="mobile-table">Action</th>
                        </tr>
                        {% for ticket in tickets %}
                        {% if ticket.status == 4 %}
                        <tr id="ticketID{{ ticket.id }}">
                            <td class="mobile-table">{{ ticket.title }}</td>
                            <td class="desktop-table">{{ ticket.id }}</td>
                            <td class="desktop-table"><span class="dot" id="{{ ticket.get_priority_display }}"></span>{{ ticket.get_priority_display }}</td>
                            <td class="mobile-table">{{ ticket.project.title }}</td>
                            {% if ticket.status == 1 %}
                            <td class="mobile-table">Unassigned</td>
                            {% else %}
                            <td class="mobile-table">{{ ticket.user.first_name }} {{ ticket.user.last_name }}</td>
                            {% endif %}
                            <td class="desktop-table">{{ ticket.created_at }}</td>
                            <td class="desktop-table">{{ ticket.updated_at }}</td>
                            <td class="mobile-table"><button class="ticket-view" id="view-ticket"><a href="/tickets/{{ ticket.id }}">View</a></button> <button class="ticket-view" id="edit-ticket"><a href="/tickets/{{ ticket.id }}/edit">Edit</a></button></td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                    </table>
                </div>
                <button class="open-form" id="openTicket">Create Ticket</button>
               
               <h2>{{ project.title }} Message Board</h2>
               <div class="comments">
                    <div class="project-comments box-shadow">
                        <ul>
                            {% for comment in comments %}
                            <li>
                                <span class="comment-user">{{ comment.user.first_name }} {{ comment.user.last_name }}</span> <span class="comment-{{ comment.user.get_user_role_display }}">({{ comment.user.get_user_role_display }})</span>
                                <span class="comment-time">{{ comment.created_at }}</span> 
                                {% if comment.user.id == request.session.user_id or request.session.role in admin%}
                                    <form action="/comments/{{ comment.id }}/delete" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="delete-comment">Delete</button>
                                    </form>
                                {% endif %}
                                <span class="comment-text">{{ comment.comment }} </span>
                            {% endfor %}
                        </ul>
                    </div>
                    <form action="/comments/add" method="post">
                        {% csrf_token %}
                        <textarea class="box-shadow" name="comment" cols="30" rows="10" placeholder="Type a message..."></textarea>
                        <input type="hidden" name="project" value="{{ project.id }}">
                        <button class="open-form" type="submit">Comment</button>
                    </form>
               </div>
            </div>
        </div>
        <div class="add-project" id="addTicket">
            <form action="/tickets/add" method="post">
                {% csrf_token %}
                <label for="title">Title</label>
                <input type="text" name="title" required>
                <label for="description">Description</label>
                <input type="text" name="description" required autocomplete="off">
                <label for="priority">Priority</label>
                <select name="priority" required>
                    <option value=""></option>
                    <option value="1">Low</option>
                    <option value="2">Medium</option>
                    <option value="3">High</option>
                </select>
                <label for="user">Assign To:</label>
                <select name="user">
                    <option value=""></option>
                    {% for user in users %}
                    <option value="{{ user.id }}">{{ user.first_name }} {{ user.last_name }}</option>
                    {% endfor %}
                </select>
                <input type="hidden" name="project" value="{{ project.id }}">
                <button type="submit" class="submit">Create Ticket</button>
            </form>
            <button class="close-form" id="closeTicket">Close</button>
        </div>
        </div>
    </div>
{% endblock %}

bug_tracker_app/templates/ticket_view.html
{% extends "base_layout.html" %}
{% block content %}
    <script>
        $(document).ready(function(){
            $("#mobile-nav-btn").click(function() {
                $("#mobile-nav").toggle();
            })
        })
    </script>
    <div class="container">

        {% include "header.html" %}

        <div class="sub-header box-shadow">
            <h2>{{ ticket.title }}</h2>
            <h2><a href="/projects/{{ ticket.project.id }}">View tickets from this project</a></h2>
        </div>
        <div class="tickets-comments">
            <div class="individual-ticket box-shadow">
                <h2><span class="ticket-header">Title: </span>{{ ticket.title }}</h2>
                <p><span class="ticket-header">ID: </span>{{ ticket.id }}</p>
                <p><span class="ticket-header">Priority: </span>{{ ticket.get_priority_display }}</p>
                <p><span class="ticket-header">Description: </span>{{ ticket.description }}</p>
                <p><span class="ticket-header">Assigned To: </span>
                    {% if ticket.user == None %}
                        Unassigned
                    {% else %}
                        {{ ticket.user.first_name }} {{ ticket.user.last_name }}
                    {% endif %}
                </p>
                <p><span class="ticket-header">Created At: </span> {{ ticket.created_at }}</p>
                <p><span class="ticket-header">Updated At: </span> {{ ticket.updated_at }}</p>
                {% if ticket.status == 2 %}
                {% if request.session.user_id == ticket.user.id %}
                <div id="ticket-submit-edit">
                    <form action="/tickets/{{ ticket.id }}/submit" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="ticket-status" value="3">
                        <button id="ticket-submit" type="submit">Submit for Review</button>
                    </form>
                    <form action="/tickets/{{ ticket.id }}/edit">
                        <button type="submit" id="ticket-edit">Edit</button>
                    </form>
                </div>
                {% endif %}
                {% endif %}
                {% if ticket.status == 3 %}
                <h3>Ticket is under review</h3>
                {% elif ticket.status == 4 %}
                <h3>Ticket is resolved</h3>
                {% endif %}
                {% if ticket.project.project_manager.id == request.session.user_id and ticket.status == 3%}
                <form action="/tickets/{{ ticket.id }}/resolve" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="ticket-status" value="4">
                    <button id="ticket-resolve" type="submit">Approve (Close Ticket)</button>
                </form>
                {% endif %}
                {% if request.session.user_id == ticket.project.project_manager.id %}
                <form action="/tickets/{{ ticket.id }}/delete">
                    {% csrf_token %}
                    <input type="hidden" value="{{ ticket.id }}" name="ticketid">
                    <button id="ticket-delete" type="submit">DELETE</button>
                </form>
                {% endif %}
            </div>
            <div id="ticket-comments-container">
                <div class="ticket-comments-display box-shadow">
                    <ul>
                        {% for comment in comments %}
                        <li>
                            <span class="comment-user">{{ comment.user.first_name }} {{ comment.user.last_name }}</span> <span class="comment-{{ comment.user.get_user_role_display }}">({{ comment.user.get_user_role_display }})</span><br>
                            <div class="comment-time-delete">
                                <span class="comment-time">{{ comment.created_at }}</span>
                                {% if comment.user.id == request.session.user_id or request.session.role in admin%}
                                <form action="/tickets/comments/{{ comment.id }}/delete" method="post">
                                    {% csrf_token %}
                                    <!-- <button type="submit" class="delete-comment">Delete</button> -->
                                    <button type="submit" id="deleteUser{{ user.id }}"class="delete-user"><i class="fas fa-times"></i></button>
                                </form>
                            {% endif %}
                            </div>
                            <span class="comment-text">{{ comment.comment }} </span>
                        {% endfor %}
                    </ul>
                </div>
                <form action="/tickets/comments/add" method="post">
                    {% csrf_token %}
                    <textarea class="box-shadow" name="comment" cols="30" rows="10" placeholder="Type a message..."></textarea>
                    <input type="hidden" name="ticket" value="{{ ticket.id }}">
                    <button class="open-form" type="submit">Comment</button>
                </form>
            </div>
        </div>
    </div>    
{% endblock %}